export const API_ENDPOINTS = {
  PRODUCTS: '/user/products-web',
  PRODUCTSCATEGORY: '/user/getProductByCategoryWeb',
  SUBSCRIPTIONPACKAGE: '/user/subscription_package',
  TRANSACTION: '/user/transactions',
  BASEPACKAGE: '/user/base_package',
  CREATESUBUSER:'/user/createUserSubscription',
  CHECKPRODUCTEXIST:'/user/checkProductExist',
  CREATERAZORPAYORDER:'/user/createRazorPayOrder',
  USERSUBSCRIPTION:'/user/user_subscription',
  USERALLSUBSCRIPTION:'/user/user_all_subscription',
  DELETEUSERSUBSCRIPTION:'/user/deleteUserSubscription',
  USERSUBSCRIPTIONLOGIN:'/user/user_subscription_loggedin',
  SUBSCRIPTIONINVOICE:'/user/GenerateInvoiceForSubscription',
  // PRODUCTS: '/products',
  PRODUCTS_POPULAR: '/popular-products',
  PRODUCTS_PRICES: '/user/getProductPrices',
  PRODUCTS_REVIEWS: '/user/reviews',
  // PRODUCTS_REVIEWS: '/reviews',
  PRODUCTS_REVIEWS_ABUSE_REPORT: '/abusive_reports',
  PRODUCTS_QUESTIONS: '/questions',
  FEEDBACK: '/feedbacks',
  CATEGORIES: '/user/category',
  // CATEGORIES: '/categories',
  TYPES: '/types',
  TAGS: '/tags',
  SHOPS: '/shops',
  AUTHORS: '/authors',
  AUTHORS_TOP: '/top-authors',
  MANUFACTURERS: '/manufacturers',
  MANUFACTURERS_TOP: '/top-manufacturers',
  COUPONS: '/coupons',
  COUPONS_VERIFY: '/coupons/verify',
  ORDERS: '/user/ordersWeb',
  // ORDERS: '/orders',
  ORDERS_STATUS: '/order-status',
  ORDER_INVOICE_DOWNLOAD:'/user/GenerateInvoice',
  DOWNLOAD:'/user/download',
  ORDERS_REFUNDS: '/refunds',
  ORDERS_CHECKOUT_VERIFY: '/user/orders/checkout/verify',
  // ORDERS_CHECKOUT_VERIFY: '/orders/checkout/verify',
  ORDERS_DOWNLOADS: '/downloads',
  GENERATE_DOWNLOADABLE_PRODUCT_LINK: '/downloads/digital_file',
  USERS: '/user/editProfile',
  // USERS: '/users',
  USERS_ADDRESS: '/address',
  USERS_ME: '/user/getUserDetail',
  // USERS_ME: '/user/loginUser',
  // USERS_ME: '/me',
  USERS_LOGIN: '/user/login',
  // USERS_LOGIN: '/token',
  USERS_REGISTER: '/user/register',
  // USERS_REGISTER: '/register',
  USERS_FORGOT_PASSWORD: '/user/forgetPassword',
  CART: '/user/cart',
  // USERS_FORGOT_PASSWORD: '/forget-password',
  USERS_VERIFY_FORGOT_PASSWORD_TOKEN: '/user/verifyPassword',
  // USERS_VERIFY_FORGOT_PASSWORD_TOKEN: '/verify-forget-password-token',
  USERS_RESET_PASSWORD: '/user/resetPassword',
  // USERS_RESET_PASSWORD: '/reset-password',
  USERS_CHANGE_PASSWORD: '/user/changePassword',
  CHECKOUT_PAY: '/user/checkoutPay',
  RAZORPAY: '/user/createRazorPayTransactions',
  STRIPESUCCESS: '/user/webhookSuccess',
  STRIPEFAILED: '/user/webhookFailed',
  // USERS_CHANGE_PASSWORD: '/change-password',
  USERS_LOGOUT: '/logout',
  USERS_SUBSCRIBE_TO_NEWSLETTER: '/subscribe-to-newsletter',
  USERS_CONTACT_US: '/user/contact-us',
  // USERS_CONTACT_US: '/contact-us',
  USERS_WISHLIST: '/user/my-wishlists',
  // USERS_WISHLIST: '/my-wishlists',
  WISHLIST: '/user/wishlists',
  USERS_WISHLIST_TOGGLE: '/user/wishlists/toggle',
  // USERS_WISHLIST_TOGGLE: '/wishlists/toggle',
  SOCIAL_LOGIN: '/social-login-token',
  SEND_OTP_CODE: '/send-otp-code',
  VERIFY_OTP_CODE: '/verify-otp-code',
  OTP_LOGIN: '/otp-login',
  UPDATE_CONTACT: '/update-contact',
  SETTINGS: '/settings',
  UPLOADS: '/attachments',
  MY_QUESTIONS: '/my-questions',
  MY_REPORTS: '/my-reports',
  COUNTRY: '/admin/countries',
  COUNTRY_STATE: '/admin/state_country',
  ONSUCCESS  :'/onSuccess'
};
